############### AUTH ###############


### Login
POST {{baseUrl}}/{{version}}/login
Accept: */*
content-type: application/json
Authorization: Bearer {{$dotenv SERVICE_CONSUMER_TOKEN}}

{
    "email": "user@email.com",
    "password": "isUser@2000"
}

### Register new user
POST {{baseUrl}}/{{version}}/register
Accept: */*
content-type: application/json
Authorization: Bearer {{$dotenv SERVICE_CONSUMER_TOKEN}}

{
    "email": "user@email.com"
}

### Logout (one)
DELETE {{baseUrl}}/{{version}}/logout
Accept: */*
content-type: application/json


### Logout (all)
DELETE {{baseUrl}}/{{version}}/logout-all
Accept: */*
content-type: application/json