############### AUTH ###############

### Login (one) ADMIN
POST {{baseUrl}}/{{version}}/login
Accept: */*
content-type: application/json
Authorization: Bearer {{$dotenv SERVICE_CONSUMER_TOKEN}}

{
    "email": "admin@email.com",
    "password": "isAdmin@2000"
}

### Login (one) USER
POST {{baseUrl}}/{{version}}/login
Accept: */*
content-type: application/json
Authorization: Bearer {{$dotenv SERVICE_CONSUMER_TOKEN}}

{
    "email": "user@email.com",
    "password": "isUser@2000"
}

### Logout (one)
POST {{baseUrl}}/{{version}}/logout
Accept: */*
content-type: application/json
Authorization: Bearer {{ $dotenv USER_TOKEN }}


### Logout (all)
POST {{baseUrl}}/{{version}}/logout-all
Accept: */*
content-type: application/json
Authorization: Bearer {{ $dotenv USER_TOKEN }}